config/routes.rb
Hashiru::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions,      only: [:new, :create, :destroy]
  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :activities,    only: [:index, :create, :destroy]
  resources :addresses,     only: [:show]

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us')%>
<h1>About Us</h1>
<div class="hero-unit">
<p>
  Shotgun Analytics is a team of Carnegie Mellon University Silicon Valley students that
  share a love of shooting and technology. We are building a revolutionary mobile app that
  will improve your shooting, and will be easy, fast and fun to use.
</p>
<p>
  <b>We need your help!</b>
  We want to make our app useful to people like you. We want to talk to
  people like you! Contributors will be considered for participation in our exclusive Beta
  testing program, which means you’ll have early access to our experimental, proprietary
  technology. Email research@shotgunanalytics.org and someone on our team will get in touch
  with you shortly.
</p>
<p>
  <b>Abhishek Shiroor :</b>
  Abhishek loves to shoot trap on his 12 gauge Remington 870. Legend has it that Abhishek’s first
  word was “Pull!”, and that he was hitting easy 20’s before he could walk.
</p>
<p>
  <b>David Housman :</b>
  David got his undergraduate education at Carnegie Mellon in Pittsburgh. He has 8 years of
  experience in the software field with such companies as Oracle, Samsung and TiVo, and is
  currently the Web Analytics Program Manager at eHealth.com. He specializes in User Experience
  and Web Analytics. David loves to shoot target, and his favorite gun to shoot is his .308
  Remington 700 VTR. He wants to get into hunting, and his desire for cheap bulk venison was
  the inspiration behind TriggerTally. You can find David’s personal website at www.davidhousman.com.
</p>
<p>
  <b>John Lee :</b>
  John grew up in the NY/NJ area and graduated from Rutgers University.  He has over 10 years of
  experience in the consulting and software field.  In his free time he likes to run marathons and
  play ultimate frisbee. It’s not clear whether John is just too cheap to buy himself a gun, or
  if he has a secret criminal past that nobody knows about. John’s favorite gun is a slingshot,
  followed by the more cost-effective method of running up to his target, tackling it, and
  punching it right in the bullseye.
</p>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<div class="center hero-unit">
  <p>
    Contact Shotgun Analytics at <%= mail_to "research@shotgunanalytics.org" %>.
  </p>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help')%>
<h1>Help</h1>
<div class="center hero-unit">
  <p>
    Get help on this website by contacting research@shotgunanalytics.org.
  </p>
</div>

app/views/static_pages/home.html.erb
<% if signed_in? %>
    <div class="row">
      <aside class="span5">
        <section>
          <%= render 'shared/user_info' %>
        </section>
        <section>
          <%= render 'shared/stats' %>
        </section>
        <section>
          <%= render 'shared/micropost_form' %>
        </section>
        <section>
          <h3>Recent Running Articles</h3> <br/>
          <ul>
            <% for entry in FeedEntry.all(:limit => 30, :order => "published_at desc") %>
                <li><%= link_to h(entry.name), entry.url, :target => '_blank' %></li>
            <% end %>
          </ul>
        </section>
      </aside>
      <div class="span7">
        <h3>Micropost Feed</h3>
        <%= render 'shared/feed' %>
      </div>
    </div>
<% else %>
    <div class="navbar-inner">
    <div class="container">
      <%= link_to "Please take our survey!", root_path, id: "logo" %>
    </div>
    </div>

    <div class="center hero-unit">
      <h1>Welcome to Shotgun Analytics</h1>
      <h2>
        Shotgun Analytics is a team of Carnegie Mellon University Silicon Valley students that
        share a love of shooting and technology. We are building a revolutionary mobile app
        that will improve your shooting, and will be easy, fast and fun to use.
      </h2>
      <h2>
        We need your help! We want to make our app useful to people like you. We want to talk
        to people like you! Contributors will be considered for participation in our exclusive
        Beta testing program, which means you’ll have early access to our experimental,
        proprietary technology. Email <%= mail_to "research@shotgunanalytics.org" %> and
        someone on our team will get in touch with you shortly.
      </h2>
      <h2>
        You can find out more about us <%= link_to "here",   about_path %>.
      </h2>

      <%#= link_to "Sign up now!", signup_path,
                  class: "btn btn-large btn-primary" %>

    </div>

  <div class="container" >
    <div class="span12">
    <ul class="thumbnails">
      <li class="span7">
        <h3>
          <p>
          Shotgun Analytics: Our Products will Blow You Away<br><br>
          Major developments in the history of firearms:
          <ul>
            <li>1410: Breech loading firearms are pioneered in Burgundy</li>
            <li>1520: Barrel Rifling invented in Augsburg, Germany</li>
            <li>1836: Samuel Colt sells his first revolver</li>
            <li>1856: Smokeless powder</li>
            <li>2013: TriggerTally revolutionizes the way you shoot</li>
          </ul>
        </p>
        </h3>

      </li>
      <li class="span4">
        <a href="#" class="thumbnail">
          <%= image_tag "trigger01.png" %>
        </a>
      </li>
    </ul>
    </div>

  </div>
<% end %> 